const dashboardCards = [
  // ---- Sidebar menu items ----
  {
    name: "Users",
    path: "/users",
    icon: "icon-user",
    valueKey: "users", 
    description: "Registered users",
    bgClass: "bg-pink-light",
  },
  {
    name: "God-Master",
    path: "/godmaster",
    icon: "icon-people",
    valueKey: "godMasters", 
    description: "God Master",
    bgClass: "bg-primary-light",
  },
  {
    name: "God",
    path: "/god",
    icon: "icon-people",
    valueKey: "gods", 
    description: "God",
    bgClass: "bg-success-light",
  },
  {
    name: "Aarti",
    path: "/aarti",
    icon: "icon-people",
    valueKey: "arti", 
    description: "Aarti",
    bgClass: "bg-info-light",
  },
  {
    name: "Mantra",
    path: "/mantra",
    icon: "icon-people",
    valueKey: "mantra",
    description: "Mantra",
    bgClass: "bg-warning-light",
  },
  {
    name: "Bhajan",
    path: "/bhajan",
    icon: "icon-people",
    valueKey: "bhajan", 
    description: "Bhajan",
    bgClass: "bg-danger-light",
  },
  {
    name: "Sloka",
    path: "/sloka",
    icon: "icon-people",
    valueKey: "sloka", 
    description: "Sloka",
    bgClass: "bg-pink-light",
  },
  {
    name: "Temple",
    path: "/temple",
    icon: "icon-people",
    valueKey: "temples", 
    description: "Temple",
    bgClass: "bg-primary-light",
  },
  {
    name: "Stuti",
    path: "/stuti",
    icon: "icon-people",
    valueKey: "stuti", 
    description: "Stuti",
    bgClass: "bg-success-light",
  },
  {
    name: "Articles",
    path: "/articles",
    icon: "icon-people",
    valueKey: "articles", 
    description: "Articles",
    bgClass: "bg-info-light",
  },
  {
    name: "Festival",
    path: "/festival",
    icon: "icon-people",
    valueKey: "festivals", 
    description: "Festival",
    bgClass: "bg-warning-light",
  },
  {
    name: "Ringtones",
    path: "/ringtones",
    icon: "icon-people",
    valueKey: "ringtones", 
    description: "Ringtones",
    bgClass: "bg-danger-light",
  },
  {
    name: "Quiz",
    path: "/quiz",
    icon: "icon-people",
    valueKey: "quizzes", 
    description: "Quiz",
    bgClass: "bg-pink-light",
  },
  {
    name: "Story",
    path: "/story",
    icon: "icon-people",
    valueKey: "story",
    description: "Story",
    bgClass: "bg-primary-light",
  },
  {
    name: "News",
    path: "/news",
    icon: "icon-people",
    valueKey: "news", 
    description: "News",
    bgClass: "bg-success-light",
  },
];

export default dashboardCards;
