// src/common/dashboardCards.js

const dashboardCards = [
  // ---- Sidebar menu items ----
  {
    name: "Users",
    path: "/users",
    icon: "icon-user",
    valueKey: "userCount",
    description: "Registered users",
    bgClass: "bg-pink-light",
  },
  {
    name: "God-Master",
    path: "/godmaster",
    icon: "icon-people",
    valueKey: "godMasterCount",
    description: "God Master",
    bgClass: "bg-primary-light",
  },
  {
    name: "God",
    path: "/god",
    icon: "icon-people",
    valueKey: "godCount",
    description: "God",
    bgClass: "bg-success-light",
  },
  {
    name: "Aarti",
    path: "/aarti",
    icon: "icon-people",
    valueKey: "aartiCount",
    description: "Aarti",
    bgClass: "bg-info-light",
  },
  {
    name: "Mantra",
    path: "/mantra",
    icon: "icon-people",
    valueKey: "mantraCount",
    description: "Mantra",
    bgClass: "bg-warning-light",
  },
  {
    name: "Bhajan",
    path: "/bhajan",
    icon: "icon-people",
    valueKey: "bhajanCount",
    description: "Bhajan",
    bgClass: "bg-danger-light",
  },
  {
    name: "Sloka",
    path: "/sloka",
    icon: "icon-people",
    valueKey: "slokaCount",
    description: "Sloka",
    bgClass: "bg-pink-light",
  },
  {
    name: "Temple",
    path: "/temple",
    icon: "icon-people",
    valueKey: "templeCount",
    description: "Temple",
    bgClass: "bg-primary-light",
  },
  {
    name: "Stuti",
    path: "/stuti",
    icon: "icon-people",
    valueKey: "stutiCount",
    description: "Stuti",
    bgClass: "bg-success-light",
  },
  {
    name: "Articles",
    path: "/articles",
    icon: "icon-people",
    valueKey: "articlesCount",
    description: "Articles",
    bgClass: "bg-info-light",
  },
  {
    name: "Festival",
    path: "/festival",
    icon: "icon-people",
    valueKey: "festivalCount",
    description: "Festival",
    bgClass: "bg-warning-light",
  },
  {
    name: "Ringtones",
    path: "/ringtones",
    icon: "icon-people",
    valueKey: "ringtonesCount",
    description: "Ringtones",
    bgClass: "bg-danger-light",
  },
  {
    name: "Quiz",
    path: "/quiz",
    icon: "icon-people",
    valueKey: "quizCount",
    description: "Quiz",
    bgClass: "bg-pink-light",
  },
  {
    name: "Story",
    path: "/story",
    icon: "icon-people",
    valueKey: "storyCount",
    description: "Story",
    bgClass: "bg-primary-light",
  },
  {
    name: "News",
    path: "/news",
    icon: "icon-people",
    valueKey: "newsCount",
    description: "News",
    bgClass: "bg-success-light",
  },
];

export default dashboardCards;
